### ISSUE TITLE
6.1 Preliminary Rounds - remove a clause

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#85] opened 2021-03-17 04:18 UTC
Last sentence reads:
  If ties are not being broken in prelims, more than 1 team can receive 1st place, 2nd place, or 3rd place points.
Suggested reading:
   If ties are not being broken in prelims, more than 1 team can receive 1st place or 2nd place points.

(With 3 teams, there is no way to tie at 3rd, unless we're mean and give a 1st and two 3rds.)

**Comment by scottpeterson** [comment] 2021-03-17 04:19
Good catch. 

Didn't we patch this already Gryphon? I know I brought it up.

**Comment by scottpeterson** [comment] 2021-03-17 04:20
Ah, this is a duplicate of https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/24

**Closed** 2021-03-18 13:26 UTC
Labels: Content
